site_name: Jak na WAGO
nav:
  - 'index.md'
  - Hardware:
    - Procesorové jednotky: hardware/plc.md
    - Vzdálené vstupy: hardware/coupler.md
    - Dotykové panely: hardware/hmi.md
    - Edge: hardware/edge.md
    - Ostatní: hardware/ostatni.md
  - Nastavení:
    - Konfigurace jednotky: nastaveni/wbm.md
    - Update firmware: nastaveni/firmware.md
  - CODESYS V3.5:
    - 'instalace.md'
    - 'projekt.md'
    - 'programovani.md'
  - 'faq.md'
theme:
  name: material
  language: cs
  icon:
    logo: material/timeline-question
  favicon: pix/favicon.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Přepnout na tmavé zobrazení

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Přepnout na světlé zobrazení
  features:
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    
copyright: |
  &copy; 2024 <a href="https://github.com/jaknawago"  target="_blank" rel="noopener">Jak na WAGO</a>